"""A generated key comes back from a rendering exactly as it went in.

WHAT THIS FILE HOLDS

Some of what the index sends to be rendered into English is not language. A
fact's `name` is generated by this system to be matched later, character for
character. A renderer given one will do reasonable things to it -- split it at
its hyphens, tidy its digits, put its words in a better order -- and every one
of those makes it stop matching.

So each occurrence is held back from the rendering and put in afterwards. The
claims this file pins are about *which* occurrence, and they are the claims that
a simpler implementation gets wrong:

  * **A key is a position, not a spelling.** Generated keys spell ordinary
    words. Protecting every place a passage happens to spell one means refusing
    to render prose the document was merely speaking.
  * **One occurrence, one marker.** The same key legitimately appears more than
    once in a single text, so a marker standing for "that key, wherever it is"
    cannot be checked for having come back the right number of times.
  * **Items do not share provenance.** The policy and its rules are separate
    documents rendered in one call. A key generated for one says nothing about
    where those letters fall in another.
  * **Anything that did not come back is refused.** A dropped, duplicated,
    altered or foreign marker means the text that would result is not the text
    that was sent, and that is a build failure rather than a repair.
"""

from __future__ import annotations

import asyncio
import json
from types import SimpleNamespace

import pytest

from policy_platform.infrastructure.search import english_projection
from policy_platform.infrastructure.search.english_projection import (
    EnglishProjectionError,
    _OpaqueText,
    project_texts_to_english,
)
from tests.fixtures.search_stubs import contained_payload

#: A generated fact name. It spells two ordinary words, which is the whole
#: difficulty: a passage may say "annual leave" without meaning this key.
KEY = "annual-leave-7"

#: The same shape without a digit.
#:
#: Two protections now run over one text: keys are withheld by the positions
#: composition recorded, and numbers are withheld wherever they occur, because a
#: rendering that drops a quantity has changed what the passage can be found by.
#: A key that ends in a digit therefore reaches the renderer with that digit
#: already withheld — correct, and it makes a test about *key* positions unable
#: to tell which mechanism acted. The tests below that are specifically about
#: position-versus-spelling use this one, so what they measure is only the thing
#: they are named for. The interaction itself is pinned separately, by
#: `test_an_unrecorded_keys_digits_are_still_protected_as_numbers`.
LETTER_KEY = "annual-leave-carry"


def _run(coro):
    return asyncio.run(coro)


def _settings():
    return SimpleNamespace(
        search_enabled=True,
        ai_enabled=True,
        azure_openai_embedding_dimensions=3,
        azure_openai_secondary_deployment="fast",
        azure_openai_deployment="slow",
    )


class _Echo:
    """A renderer that returns what it was given, remembering what that was.

    Identity is the right stub here. These tests are not about how well a
    passage is rendered; they are about whether the characters that must not be
    rendered were withheld from it and restored afterwards. What the renderer
    was *sent* is the evidence, so it is recorded.
    """

    def __init__(self) -> None:
        self.payloads: list[dict] = []

    async def chat(self, messages, **_kwargs) -> str:
        payload = contained_payload(messages[-1]["content"])
        self.payloads.append(payload)
        return json.dumps(payload, ensure_ascii=False)

    def sent(self) -> str:
        """Everything the renderer saw, as one string."""

        return "\n".join(
            value for payload in self.payloads for value in payload.values()
        )


def _spans(text: str, term: str) -> list[tuple[int, int]]:
    """Every position of `term` in `text`.

    A test helper, deliberately not the product's method: the product carries
    positions down from where it composed the string. Finding them by value is
    fine for building a fixture and is exactly what must not happen in the
    product, which is why these tests then check the *prose* was left alone.
    """

    found, start = [], text.find(term)
    while start != -1:
        found.append((start, start + len(term)))
        start = text.find(term, start + 1)
    return found


# --------------------------------------------------------------------------
# A key is a position, not a spelling
# --------------------------------------------------------------------------


def test_prose_that_happens_to_spell_a_key_is_still_rendered():
    """The words a key is made of are not the key, and are not withheld.

    Measured on the live corpus rather than imagined: forty-one records there
    contain an opaque value inside unrelated prose, among them `employee`,
    `condition`, `action`, `object`, `leave` and `you`. A generated name is
    allowed to be an ordinary word, so protecting by spelling would refuse to
    render the places the document was merely speaking.

    The fixture uses such a name deliberately. Withholding by value replaces
    both occurrences here; withholding by position replaces only the one
    composition recorded.
    """

    plain_word_key = "leave"
    text = "Staff may leave early. The leave entitlement resets each year."
    recorded = _spans(text, plain_word_key)[1:]
    assert len(recorded) == 1, "fixture should record only the second occurrence"

    protector = _OpaqueText({"rule-0": recorded}, texts=[text])
    hidden = protector.hide("rule-0", text)

    assert "Staff may leave early." in hidden, (
        "prose was withheld as if it were a key; the document said this word, "
        "it did not name it"
    )
    assert "leave entitlement" not in hidden, "the recorded occurrence was not withheld"
    assert protector.show("rule-0", hidden) == text


def test_an_unrecorded_occurrence_is_left_for_the_renderer():
    """Only what composition recorded is protected -- nothing is found by value."""

    text = f"{LETTER_KEY} applies. Elsewhere the document also writes {LETTER_KEY} as prose."
    first_only = _spans(text, LETTER_KEY)[:1]

    protector = _OpaqueText({"rule-0": first_only}, texts=[text])
    hidden = protector.hide("rule-0", text)

    assert hidden.count(LETTER_KEY) == 1, "an occurrence nobody recorded was withheld anyway"
    assert protector.show("rule-0", hidden) == text


def test_an_unrecorded_key_is_protected_as_an_identifier_not_as_a_key():
    """The two protections overlap on a key that mixes letters and digits.

    Composition recorded one occurrence. The other is prose as far as *key*
    protection is concerned, and nothing finds it by value. It is protected all
    the same — not as a key, but because `annual-leave-7` is identifier-shaped,
    and identifier-shaped tokens are exactly what the validator will later
    require the rendering to have carried.

    That is the general rule rather than a special case for keys: every literal
    the validator requires is withheld, whoever generated it. Pinning it stops
    someone "simplifying" the identifier predicate into one that only covers
    tokens somebody recorded, which would put the unrecorded occurrence back at
    the mercy of the renderer.
    """

    text = f"{KEY} applies. Elsewhere the document also writes {KEY} as prose."
    first_only = _spans(text, KEY)[:1]

    protector = _OpaqueText({"rule-0": first_only}, texts=[text])
    hidden = protector.hide("rule-0", text)

    assert KEY not in hidden, "an identifier-shaped token was left for the renderer"
    assert not english_projection._identifiers(hidden), (
        "the hidden text still states an identifier the rendering must reproduce"
    )
    assert len(protector._expected["rule-0"]) == 2, (
        "the recorded occurrence and the identifier-shaped one should each be withheld once"
    )
    assert protector.show("rule-0", hidden) == text


def test_prose_around_an_unrecorded_key_still_reaches_the_renderer():
    """Protection is still of literals, not of the words beside them."""

    text = f"{KEY} applies. Elsewhere the document also writes {KEY} as prose."
    protector = _OpaqueText({"rule-0": _spans(text, KEY)[:1]}, texts=[text])
    hidden = protector.hide("rule-0", text)

    assert "Elsewhere the document also writes" in hidden
    assert "as prose." in hidden


# --------------------------------------------------------------------------
# One occurrence, one marker
# --------------------------------------------------------------------------


def test_a_key_that_occurs_twice_is_withheld_and_restored_twice():
    """Fourteen hundred records here repeat an opaque value; the unit this
    boundary was built for carries its key twice. One marker for both could not
    tell a rendering that returned it once from one that returned it twice."""

    text = f"Under {KEY} the balance accrues. Requests cite {KEY} on the form."
    recorded = _spans(text, KEY)
    assert len(recorded) == 2

    protector = _OpaqueText({"rule-0": recorded}, texts=[text])
    hidden = protector.hide("rule-0", text)

    assert KEY not in hidden
    markers = {token for token in hidden.split() if protector._prefix in token}
    assert len(markers) == 2, "both occurrences were given the same marker"
    assert protector.show("rule-0", hidden) == text


def test_the_same_key_in_two_items_cannot_cross_between_them():
    """A marker belongs to one item. One that arrives in another is refused."""

    first = f"Rule one cites {KEY} here."
    second = f"Rule two also cites {KEY} here."
    protector = _OpaqueText(
        {"rule-0": _spans(first, KEY), "rule-1": _spans(second, KEY)},
        texts=[first, second],
    )

    hidden_first = protector.hide("rule-0", first)
    hidden_second = protector.hide("rule-1", second)

    marker_of_first = next(
        token for token in hidden_first.split() if protector._prefix in token
    )
    marker_of_second = next(
        token for token in hidden_second.split() if protector._prefix in token
    )
    assert marker_of_first != marker_of_second, "two items were given one marker"

    # The second item coming back carrying the first item's marker.
    swapped = hidden_second.replace(marker_of_second, marker_of_first)
    with pytest.raises(EnglishProjectionError):
        protector.show("rule-1", swapped)


def test_two_keys_next_to_each_other_are_each_restored():
    """Adjacent positions are a case a backwards substitution has to get right."""

    other = "grade-band-3"
    text = f"See {KEY} {other} for the table."
    recorded = sorted(_spans(text, KEY) + _spans(text, other))

    protector = _OpaqueText({"rule-0": recorded}, texts=[text])
    assert protector.show("rule-0", protector.hide("rule-0", text)) == text


# --------------------------------------------------------------------------
# Anything that did not come back is refused
# --------------------------------------------------------------------------


def test_a_rendering_that_drops_a_key_is_refused():
    text = f"The entitlement under {KEY} is fixed."
    protector = _OpaqueText({"rule-0": _spans(text, KEY)}, texts=[text])
    hidden = protector.hide("rule-0", text)
    marker = next(token for token in hidden.split() if protector._prefix in token)

    with pytest.raises(EnglishProjectionError):
        protector.show("rule-0", hidden.replace(marker, ""))


def test_a_rendering_that_duplicates_a_key_is_refused():
    text = f"The entitlement under {KEY} is fixed."
    protector = _OpaqueText({"rule-0": _spans(text, KEY)}, texts=[text])
    hidden = protector.hide("rule-0", text)
    marker = next(token for token in hidden.split() if protector._prefix in token)

    with pytest.raises(EnglishProjectionError):
        protector.show("rule-0", f"{hidden} and again {marker}")


def test_a_rendering_that_alters_a_marker_is_refused():
    """A marker with a digit changed is not the marker that was sent."""

    text = f"The entitlement under {KEY} is fixed."
    protector = _OpaqueText({"rule-0": _spans(text, KEY)}, texts=[text])
    hidden = protector.hide("rule-0", text)
    marker = next(token for token in hidden.split() if protector._prefix in token)
    altered = marker[:-3] + "9" + marker[-2:]

    with pytest.raises(EnglishProjectionError):
        protector.show("rule-0", hidden.replace(marker, altered))


def test_positions_that_do_not_fit_their_text_are_refused():
    """Provenance that does not fit the string is not that string's provenance."""

    text = f"Under {KEY} the balance accrues."

    past_the_end = _OpaqueText({"rule-0": [(0, len(text) + 5)]}, texts=[text])
    with pytest.raises(EnglishProjectionError):
        past_the_end.hide("rule-0", text)

    overlapping = _OpaqueText({"rule-0": [(0, 10), (5, 15)]}, texts=[text])
    with pytest.raises(EnglishProjectionError):
        overlapping.hide("rule-0", text)

    inside_out = _OpaqueText({"rule-0": [(10, 4)]}, texts=[text])
    with pytest.raises(EnglishProjectionError):
        inside_out.hide("rule-0", text)


# --------------------------------------------------------------------------
# The marker's own shape
# --------------------------------------------------------------------------


def test_a_marker_stem_the_source_already_spells_is_lengthened():
    """A marker only works because nothing else looks like it, so that is checked."""

    text = f"This text mentions {_OpaqueText._STEM} on purpose."
    protector = _OpaqueText({"rule-0": []}, texts=[text])

    assert protector._prefix != _OpaqueText._STEM
    assert protector._prefix not in text


def test_the_marker_is_inert_to_every_check_the_validator_makes():
    """A marker must not itself be a literal the validator then requires.

    THIS INVERTS AN EARLIER DECISION, AND THE MEASUREMENT IS WHY

    The marker used to carry its ordinal in digits, deliberately, so that the
    preservation check already here would catch a mangled one. That reasoning
    was sound while only recorded keys were protected -- there were few of them,
    and they were identifier-shaped in the source anyway.

    It stopped being sound once every number was protected too. The validator
    asks which numbers a text states and which identifier-shaped tokens it
    states; a digit-bearing marker answers the second. So protecting a plain
    number *created* an identifier the source never contained, and the renderer
    was then required to reproduce it exactly. Measured over one real corpus:
    2,277 identifier tokens existed only because a number had been protected,
    against 83 the documents themselves stated. A live rebuild was refused for
    losing five of them.

    The guarantee did not weaken; it moved to a stricter check.
    `protected_literal_failure` refuses a dropped or duplicated marker per item
    and per attempt, so it is still caught during rendering and still retried --
    and `show` refuses anything that survives that. Both are exact-occurrence
    rules, where the identifier check was set membership.
    """

    text = f"Under {KEY} the balance accrues within 30 days."
    protector = _OpaqueText({"rule-0": _spans(text, KEY)}, texts=[text])
    hidden = protector.hide("rule-0", text)

    assert not english_projection._identifiers(hidden), (
        "a marker is an identifier again, so protecting a literal now requires one"
    )
    assert not english_projection._numbers(hidden), (
        "a marker states a number, so protecting a literal now requires one"
    )
    assert english_projection.preservation_failure(hidden, hidden) is None

    # The guarantee, at its new home: losing one is still refused, during
    # rendering, by a check that names counts and no values.
    dropped = hidden.replace(protector._expected["rule-0"][0], "", 1)
    reason = english_projection.protected_literal_failure(hidden, dropped)
    assert reason is not None
    assert "protected literal" in reason
    assert KEY not in reason and "30" not in reason


# --------------------------------------------------------------------------
# Through the whole rendering path
# --------------------------------------------------------------------------


def test_a_key_comes_back_exactly_from_a_whole_rendering():
    """End to end, because a helper on its own does not run the caller's code."""

    text = f"Under {KEY} the balance accrues for staff."
    client = _Echo()

    rendered = _run(
        project_texts_to_english(
            [("rule-0", text)],
            settings=_settings(),
            openai_client=client,
            opaque_spans={"rule-0": _spans(text, KEY)},
        )
    )

    assert rendered["rule-0"] == text
    assert KEY not in client.sent(), "the key was sent to the renderer after all"


def test_a_rules_positions_do_not_reach_into_the_policy_text():
    """One item's provenance cannot protect another item's prose.

    The policy here spells the rule's key as ordinary words. Nothing recorded
    it there, so it must go to the renderer as language -- and the rule's own
    occurrence must not. Both halves are checked against what was actually
    sent, because that is where a shared term set would show.
    """

    policy = f"The handbook explains {LETTER_KEY} in plain terms for readers."
    rule = f"Under {LETTER_KEY} the balance accrues."
    client = _Echo()

    rendered = _run(
        project_texts_to_english(
            [("policy", policy), ("rule-0", rule)],
            settings=_settings(),
            openai_client=client,
            opaque_spans={"rule-0": _spans(rule, LETTER_KEY)},
        )
    )

    assert rendered["policy"] == policy
    assert rendered["rule-0"] == rule

    sent = [value for payload in client.payloads for value in payload.values()]
    carrying = [value for value in sent if LETTER_KEY in value]
    assert len(carrying) == 1, (
        "exactly one item should have reached the renderer still spelling the key"
    )
    assert carrying[0].startswith("The handbook explains"), (
        "the policy's plain-language occurrence should have been rendered and the "
        "rule's recorded one withheld; a shared term set gets this backwards"
    )


def test_a_text_with_no_recorded_positions_is_rendered_untouched():
    """Nothing is protected by default, so a clean text is not marked up at all."""

    text = "Staff may take annual leave each year."
    client = _Echo()

    rendered = _run(
        project_texts_to_english(
            [("rule-0", text)], settings=_settings(), openai_client=client
        )
    )

    assert rendered["rule-0"] == text
    assert client.sent() == text
